version: 2

jobs:
  test:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1-node-browsers-legacy
        environment:
          LEIN_ROOT: nbd
          JVM_OPTS: -Xms1g -Xmx1g
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run:
          name: Fetch dependencies
          command: lein deps
      - save_cache:
          key: v1-dependencies-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - run:
          name: Test clj
          command: lein test
      - run:
          name: Test cljs
          command: lein test:cljs

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
